# Generated by Django 2.0.1 on 2018-02-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_plan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
